---
# This playbook install Tomcat.

- hosts: node1
  become: true
  gather_facts: no
  tasks:
  - name: install openjdk
    yum: 
      name: java-11-openjdk,java-11-openjdk-devel
      state: latest
  - name: install tomcat
    yum:
      
