---
# This playbook creates user and assigns permission to a particular file.

- hosts: node3
  become: true
  gather_facts: no
  tasks:
  - name: install nginx wget
    user: 
      name: ansihktn
      state: present
  - name: create a file and assign permission to user
    file: 
      path: /tmp/ansi_file
      state: touch
      owner: ansihktn
      mode: 0755
