---
# This playbook configures NTP server.

- hosts: node1
  become: true
  gather_facts: no
  tasks:
  - name: install chrony
    yum: 
      name: chrony
      state: latest
  - name: Enable and start chronyd
    service:
      name: chronyd
      enabled: yes
      state: started
  - name: Add network or subnet details
    lineinfile:
      path: /etc/chrony.conf
      line: allow 3.125.17.7
  - name: Enable and start chronyd
    service:
      name: chronyd
      enabled: yes
      state: restarted
  - name: Check list of NTP clients
    shell: chronyc clients
    register: CHRONYC_CLIENTS
  - debug: msg="{{CHRONYC_CLIENTS.stdout_lines}}"

