---
# This playbook configures NTP clients.

- hosts: node2
  become: true
  gather_facts: no
  tasks:
  - name: install chrony
    yum: 
      name: chrony
      state: latest
  - name: Enable and start chronyd
    service:
      name: chronyd
      enabled: yes
      status: started
  - name: Add network or subnet details
    lineinfile:
      path: vi /etc/chrony.conf
      line: server 3.126.248.59
  - name: Enable and start chronyd
    service:
      name: chronyd
      enabled: yes
      status: restarted
  - name: Check list of NTP clients
    shell: chronyc sources
    register: CHRONYC_SOURCES
  - debug: msg="{{CHRONYC_SOURCES}}"

