---
# This playbook configures NTP server.

- hosts: "{{ntp_server_ip}}"
  tasks:
  - name: install chrony
    yum: 
      name: chrony
      state: latest
  - name: Enable and start chronyd
    service:
      name: chronyd
      enabled: yes
      status: started
  - name: Add network or subnet details
    lineinfile:
      path: vi /etc/chrony.conf
      line: allow "{{allowed_subnet-network}}"
  - name: Enable and start chronyd
    service:
      name: chronyd
      enabled: yes
      status: restarted
  - name: Check list of NTP clients
    shell: chronyc clients
    register: CHRONYC_CLIENTS
  - debug: msg="{{CHRONYC_CLIENTS}}"

